version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:16.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
